import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const VOCABULARY = [
  // ── English (en) ──
  { word: 'hello', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used as a greeting' }], examples: [{ sentence: 'Hello, how are you?', translation: '' }], topicTags: ['greetings'], synonyms: ['hi', 'hey'] },
  { word: 'goodbye', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used when leaving' }], examples: [{ sentence: 'Goodbye, see you tomorrow.', translation: '' }], topicTags: ['greetings'], synonyms: ['bye', 'farewell'] },
  { word: 'thank', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'verb', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: 'Thank you for your help.', translation: '' }], topicTags: ['politeness'], synonyms: ['appreciate'] },
  { word: 'please', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'adverb', definitions: [{ meaning: 'used to make polite requests' }], examples: [{ sentence: 'Please sit down.', translation: '' }], topicTags: ['politeness'] },
  { word: 'yes', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used to affirm' }], examples: [{ sentence: 'Yes, I understand.', translation: '' }], topicTags: ['basics'] },
  { word: 'no', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used to negate' }], examples: [{ sentence: 'No, I do not know.', translation: '' }], topicTags: ['basics'] },
  { word: 'water', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'a clear liquid needed for life' }], examples: [{ sentence: 'Can I have a glass of water?', translation: '' }], topicTags: ['food', 'daily-life'] },
  { word: 'food', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'things people eat' }], examples: [{ sentence: 'The food here is delicious.', translation: '' }], topicTags: ['food', 'daily-life'] },
  { word: 'eat', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'verb', definitions: [{ meaning: 'to take food into the body' }], examples: [{ sentence: 'I eat breakfast at 7am.', translation: '' }], topicTags: ['food', 'daily-life'] },
  { word: 'drink', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'verb', definitions: [{ meaning: 'to swallow liquid' }], examples: [{ sentence: 'You should drink more water.', translation: '' }], topicTags: ['food', 'daily-life'] },
  { word: 'house', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'a building where people live' }], examples: [{ sentence: 'My house has three bedrooms.', translation: '' }], topicTags: ['home', 'daily-life'] },
  { word: 'family', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'a group of related people' }], examples: [{ sentence: 'My family has four people.', translation: '' }], topicTags: ['people', 'family'] },
  { word: 'mother', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'a female parent' }], examples: [{ sentence: 'My mother is a teacher.', translation: '' }], topicTags: ['people', 'family'] },
  { word: 'father', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'a male parent' }], examples: [{ sentence: 'My father works in an office.', translation: '' }], topicTags: ['people', 'family'] },
  { word: 'happy', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'feeling pleasure or joy' }], examples: [{ sentence: 'I am happy to see you.', translation: '' }], topicTags: ['emotions'] },
  { word: 'sad', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'feeling unhappiness' }], examples: [{ sentence: 'She was sad when he left.', translation: '' }], topicTags: ['emotions'] },
  { word: 'big', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'of great size' }], examples: [{ sentence: 'That is a big dog.', translation: '' }], topicTags: ['descriptions'] },
  { word: 'small', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'of little size' }], examples: [{ sentence: 'The kitten is very small.', translation: '' }], topicTags: ['descriptions'] },
  { word: 'go', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'verb', definitions: [{ meaning: 'to move from one place to another' }], examples: [{ sentence: 'I go to school every day.', translation: '' }], topicTags: ['actions', 'travel'] },
  { word: 'come', languageCode: 'en', cefrLevel: 'A1', partOfSpeech: 'verb', definitions: [{ meaning: 'to move toward the speaker' }], examples: [{ sentence: 'Come here, please.', translation: '' }], topicTags: ['actions'] },
  { word: 'beautiful', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'very attractive or pleasing' }], examples: [{ sentence: 'The sunset was beautiful.', translation: '' }], topicTags: ['descriptions', 'nature'] },
  { word: 'important', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'of great significance' }], examples: [{ sentence: 'This is an important meeting.', translation: '' }], topicTags: ['work', 'daily-life'] },
  { word: 'remember', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'verb', definitions: [{ meaning: 'to recall information' }], examples: [{ sentence: 'I remember your name.', translation: '' }], topicTags: ['mental-actions'] },
  { word: 'forget', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'verb', definitions: [{ meaning: 'to fail to remember' }], examples: [{ sentence: 'Do not forget your keys.', translation: '' }], topicTags: ['mental-actions'] },
  { word: 'different', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'not the same' }], examples: [{ sentence: 'These two books are different.', translation: '' }], topicTags: ['comparisons'] },
  { word: 'difficult', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'hard to do or understand' }], examples: [{ sentence: 'The exam was difficult.', translation: '' }], topicTags: ['descriptions'] },
  { word: 'arrive', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'verb', definitions: [{ meaning: 'to reach a destination' }], examples: [{ sentence: 'We will arrive at 3pm.', translation: '' }], topicTags: ['travel'] },
  { word: 'weather', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'noun', definitions: [{ meaning: 'conditions outside (rain, sun, etc.)' }], examples: [{ sentence: 'The weather is nice today.', translation: '' }], topicTags: ['nature', 'daily-life'] },
  { word: 'expensive', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'costing a lot of money' }], examples: [{ sentence: 'This restaurant is expensive.', translation: '' }], topicTags: ['shopping', 'money'] },
  { word: 'cheap', languageCode: 'en', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'costing little money' }], examples: [{ sentence: 'I found a cheap hotel.', translation: '' }], topicTags: ['shopping', 'money'] },
  { word: 'suggest', languageCode: 'en', cefrLevel: 'B1', partOfSpeech: 'verb', definitions: [{ meaning: 'to offer an idea' }], examples: [{ sentence: 'I suggest we leave early.', translation: '' }], topicTags: ['communication', 'work'] },
  { word: 'opportunity', languageCode: 'en', cefrLevel: 'B1', partOfSpeech: 'noun', definitions: [{ meaning: 'a chance for advancement' }], examples: [{ sentence: 'This is a great opportunity.', translation: '' }], topicTags: ['work', 'life'] },
  { word: 'experience', languageCode: 'en', cefrLevel: 'B1', partOfSpeech: 'noun', definitions: [{ meaning: 'knowledge from doing something' }], examples: [{ sentence: 'I have experience in sales.', translation: '' }], topicTags: ['work', 'life'] },
  { word: 'develop', languageCode: 'en', cefrLevel: 'B1', partOfSpeech: 'verb', definitions: [{ meaning: 'to grow or improve' }], examples: [{ sentence: 'We need to develop new skills.', translation: '' }], topicTags: ['work', 'growth'] },
  { word: 'influence', languageCode: 'en', cefrLevel: 'B1', partOfSpeech: 'verb', definitions: [{ meaning: 'to affect someone or something' }], examples: [{ sentence: 'Social media can influence people.', translation: '' }], topicTags: ['society', 'communication'] },
  { word: 'therefore', languageCode: 'en', cefrLevel: 'B1', partOfSpeech: 'adverb', definitions: [{ meaning: 'for that reason' }], examples: [{ sentence: 'He was late; therefore he missed the bus.', translation: '' }], topicTags: ['academic', 'writing'] },

  // ── Spanish (es) ──
  { word: 'hola', languageCode: 'es', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used as a greeting' }], examples: [{ sentence: 'Hola, ¿cómo estás?', translation: 'Hello, how are you?' }], topicTags: ['greetings'], synonyms: ['buenos días'] },
  { word: 'adiós', languageCode: 'es', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used when leaving' }], examples: [{ sentence: 'Adiós, nos vemos mañana.', translation: 'Goodbye, see you tomorrow.' }], topicTags: ['greetings'] },
  { word: 'gracias', languageCode: 'es', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: 'Muchas gracias por tu ayuda.', translation: 'Thank you very much for your help.' }], topicTags: ['politeness'] },
  { word: 'agua', languageCode: 'es', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'clear liquid needed for life' }], examples: [{ sentence: '¿Me puede dar un vaso de agua?', translation: 'Can you give me a glass of water?' }], topicTags: ['food', 'daily-life'] },
  { word: 'comida', languageCode: 'es', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'things people eat' }], examples: [{ sentence: 'La comida es deliciosa.', translation: 'The food is delicious.' }], topicTags: ['food'] },
  { word: 'casa', languageCode: 'es', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'building where people live' }], examples: [{ sentence: 'Mi casa tiene tres cuartos.', translation: 'My house has three rooms.' }], topicTags: ['home'] },
  { word: 'familia', languageCode: 'es', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'group of related people' }], examples: [{ sentence: 'Mi familia es grande.', translation: 'My family is big.' }], topicTags: ['people', 'family'] },
  { word: 'feliz', languageCode: 'es', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'feeling pleasure or joy' }], examples: [{ sentence: 'Estoy feliz de verte.', translation: 'I am happy to see you.' }], topicTags: ['emotions'] },
  { word: 'grande', languageCode: 'es', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'of great size' }], examples: [{ sentence: 'Esa casa es muy grande.', translation: 'That house is very big.' }], topicTags: ['descriptions'] },
  { word: 'trabajar', languageCode: 'es', cefrLevel: 'A2', partOfSpeech: 'verb', definitions: [{ meaning: 'to do work' }], examples: [{ sentence: 'Trabajo en una oficina.', translation: 'I work in an office.' }], topicTags: ['work'] },
  { word: 'hermoso', languageCode: 'es', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'very beautiful' }], examples: [{ sentence: 'El paisaje es hermoso.', translation: 'The landscape is beautiful.' }], topicTags: ['descriptions', 'nature'] },
  { word: 'recordar', languageCode: 'es', cefrLevel: 'A2', partOfSpeech: 'verb', definitions: [{ meaning: 'to recall' }], examples: [{ sentence: 'Recuerdo tu nombre.', translation: 'I remember your name.' }], topicTags: ['mental-actions'] },
  { word: 'difícil', languageCode: 'es', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'hard to do' }], examples: [{ sentence: 'El examen fue difícil.', translation: 'The exam was difficult.' }], topicTags: ['descriptions'] },
  { word: 'llegar', languageCode: 'es', cefrLevel: 'A2', partOfSpeech: 'verb', definitions: [{ meaning: 'to arrive' }], examples: [{ sentence: 'Llegamos a las tres.', translation: 'We arrive at three.' }], topicTags: ['travel'] },
  { word: 'sugerir', languageCode: 'es', cefrLevel: 'B1', partOfSpeech: 'verb', definitions: [{ meaning: 'to suggest' }], examples: [{ sentence: 'Sugiero que salgamos temprano.', translation: 'I suggest we leave early.' }], topicTags: ['communication'] },

  // ── French (fr) ──
  { word: 'bonjour', languageCode: 'fr', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used as a greeting' }], examples: [{ sentence: 'Bonjour, comment allez-vous?', translation: 'Hello, how are you?' }], topicTags: ['greetings'] },
  { word: 'merci', languageCode: 'fr', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: 'Merci beaucoup pour votre aide.', translation: 'Thank you very much for your help.' }], topicTags: ['politeness'] },
  { word: 'eau', languageCode: 'fr', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'clear liquid needed for life' }], examples: [{ sentence: 'Je voudrais un verre d\'eau.', translation: 'I would like a glass of water.' }], topicTags: ['food'] },
  { word: 'maison', languageCode: 'fr', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'building where people live' }], examples: [{ sentence: 'Ma maison est petite.', translation: 'My house is small.' }], topicTags: ['home'] },
  { word: 'heureux', languageCode: 'fr', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'feeling joy' }], examples: [{ sentence: 'Je suis heureux de te voir.', translation: 'I am happy to see you.' }], topicTags: ['emotions'] },
  { word: 'manger', languageCode: 'fr', cefrLevel: 'A1', partOfSpeech: 'verb', definitions: [{ meaning: 'to eat' }], examples: [{ sentence: 'Je mange à 7 heures.', translation: 'I eat at 7 o\'clock.' }], topicTags: ['food'] },
  { word: 'travail', languageCode: 'fr', cefrLevel: 'A2', partOfSpeech: 'noun', definitions: [{ meaning: 'work or job' }], examples: [{ sentence: 'Je cherche un travail.', translation: 'I am looking for a job.' }], topicTags: ['work'] },
  { word: 'important', languageCode: 'fr', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'of great significance' }], examples: [{ sentence: 'C\'est une réunion importante.', translation: 'This is an important meeting.' }], topicTags: ['work'] },
  { word: 'souvenir', languageCode: 'fr', cefrLevel: 'A2', partOfSpeech: 'verb', definitions: [{ meaning: 'to remember' }], examples: [{ sentence: 'Je me souviens de ton nom.', translation: 'I remember your name.' }], topicTags: ['mental-actions'] },
  { word: 'difficile', languageCode: 'fr', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'hard to do' }], examples: [{ sentence: 'Cet examen est difficile.', translation: 'This exam is difficult.' }], topicTags: ['descriptions'] },

  // ── German (de) ──
  { word: 'hallo', languageCode: 'de', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used as a greeting' }], examples: [{ sentence: 'Hallo, wie geht es Ihnen?', translation: 'Hello, how are you?' }], topicTags: ['greetings'] },
  { word: 'danke', languageCode: 'de', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: 'Danke für Ihre Hilfe.', translation: 'Thank you for your help.' }], topicTags: ['politeness'] },
  { word: 'Wasser', languageCode: 'de', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'clear liquid needed for life' }], examples: [{ sentence: 'Kann ich ein Glas Wasser haben?', translation: 'Can I have a glass of water?' }], topicTags: ['food'] },
  { word: 'Haus', languageCode: 'de', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'building where people live' }], examples: [{ sentence: 'Mein Haus hat drei Zimmer.', translation: 'My house has three rooms.' }], topicTags: ['home'] },
  { word: 'essen', languageCode: 'de', cefrLevel: 'A1', partOfSpeech: 'verb', definitions: [{ meaning: 'to eat' }], examples: [{ sentence: 'Ich esse um 7 Uhr Frühstück.', translation: 'I eat breakfast at 7 o\'clock.' }], topicTags: ['food'] },
  { word: 'arbeiten', languageCode: 'de', cefrLevel: 'A2', partOfSpeech: 'verb', definitions: [{ meaning: 'to work' }], examples: [{ sentence: 'Ich arbeite in einem Büro.', translation: 'I work in an office.' }], topicTags: ['work'] },
  { word: 'wichtig', languageCode: 'de', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'of great significance' }], examples: [{ sentence: 'Das ist ein wichtiges Meeting.', translation: 'This is an important meeting.' }], topicTags: ['work'] },
  { word: 'schwierig', languageCode: 'de', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'hard to do' }], examples: [{ sentence: 'Die Prüfung war schwierig.', translation: 'The exam was difficult.' }], topicTags: ['descriptions'] },
  { word: 'glücklich', languageCode: 'de', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'feeling joy' }], examples: [{ sentence: 'Ich bin glücklich.', translation: 'I am happy.' }], topicTags: ['emotions'] },
  { word: 'Familie', languageCode: 'de', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'group of related people' }], examples: [{ sentence: 'Meine Familie ist groß.', translation: 'My family is big.' }], topicTags: ['family'] },

  // ── Italian (it) ──
  { word: 'ciao', languageCode: 'it', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used as a greeting or farewell' }], examples: [{ sentence: 'Ciao, come stai?', translation: 'Hello, how are you?' }], topicTags: ['greetings'] },
  { word: 'grazie', languageCode: 'it', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: 'Grazie mille per il tuo aiuto.', translation: 'Thank you very much for your help.' }], topicTags: ['politeness'] },
  { word: 'acqua', languageCode: 'it', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'clear liquid needed for life' }], examples: [{ sentence: 'Posso avere un bicchiere d\'acqua?', translation: 'Can I have a glass of water?' }], topicTags: ['food'] },
  { word: 'casa', languageCode: 'it', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'building where people live' }], examples: [{ sentence: 'La mia casa è piccola.', translation: 'My house is small.' }], topicTags: ['home'] },
  { word: 'felice', languageCode: 'it', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'feeling joy' }], examples: [{ sentence: 'Sono felice di vederti.', translation: 'I am happy to see you.' }], topicTags: ['emotions'] },
  { word: 'mangiare', languageCode: 'it', cefrLevel: 'A1', partOfSpeech: 'verb', definitions: [{ meaning: 'to eat' }], examples: [{ sentence: 'Mangio la colazione alle 7.', translation: 'I eat breakfast at 7.' }], topicTags: ['food'] },
  { word: 'lavorare', languageCode: 'it', cefrLevel: 'A2', partOfSpeech: 'verb', definitions: [{ meaning: 'to work' }], examples: [{ sentence: 'Lavoro in un ufficio.', translation: 'I work in an office.' }], topicTags: ['work'] },
  { word: 'importante', languageCode: 'it', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'of great significance' }], examples: [{ sentence: 'Questa è una riunione importante.', translation: 'This is an important meeting.' }], topicTags: ['work'] },
  { word: 'difficile', languageCode: 'it', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'hard to do' }], examples: [{ sentence: 'L\'esame era difficile.', translation: 'The exam was difficult.' }], topicTags: ['descriptions'] },
  { word: 'famiglia', languageCode: 'it', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'group of related people' }], examples: [{ sentence: 'La mia famiglia è grande.', translation: 'My family is big.' }], topicTags: ['family'] },

  // ── Portuguese (pt) ──
  { word: 'olá', languageCode: 'pt', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'used as a greeting' }], examples: [{ sentence: 'Olá, como vai?', translation: 'Hello, how are you?' }], topicTags: ['greetings'] },
  { word: 'obrigado', languageCode: 'pt', cefrLevel: 'A1', partOfSpeech: 'interjection', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: 'Muito obrigado pela ajuda.', translation: 'Thank you very much for the help.' }], topicTags: ['politeness'] },
  { word: 'água', languageCode: 'pt', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'clear liquid needed for life' }], examples: [{ sentence: 'Posso ter um copo de água?', translation: 'Can I have a glass of water?' }], topicTags: ['food'] },
  { word: 'casa', languageCode: 'pt', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'building where people live' }], examples: [{ sentence: 'Minha casa tem três quartos.', translation: 'My house has three rooms.' }], topicTags: ['home'] },
  { word: 'comer', languageCode: 'pt', cefrLevel: 'A1', partOfSpeech: 'verb', definitions: [{ meaning: 'to eat' }], examples: [{ sentence: 'Como café da manhã às 7h.', translation: 'I eat breakfast at 7am.' }], topicTags: ['food'] },
  { word: 'feliz', languageCode: 'pt', cefrLevel: 'A1', partOfSpeech: 'adjective', definitions: [{ meaning: 'feeling joy' }], examples: [{ sentence: 'Estou feliz em ver você.', translation: 'I am happy to see you.' }], topicTags: ['emotions'] },
  { word: 'trabalho', languageCode: 'pt', cefrLevel: 'A2', partOfSpeech: 'noun', definitions: [{ meaning: 'work or job' }], examples: [{ sentence: 'Estou procurando trabalho.', translation: 'I am looking for work.' }], topicTags: ['work'] },
  { word: 'importante', languageCode: 'pt', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'of great significance' }], examples: [{ sentence: 'Isto é muito importante.', translation: 'This is very important.' }], topicTags: ['work'] },
  { word: 'difícil', languageCode: 'pt', cefrLevel: 'A2', partOfSpeech: 'adjective', definitions: [{ meaning: 'hard to do' }], examples: [{ sentence: 'A prova foi difícil.', translation: 'The test was difficult.' }], topicTags: ['descriptions'] },
  { word: 'família', languageCode: 'pt', cefrLevel: 'A1', partOfSpeech: 'noun', definitions: [{ meaning: 'group of related people' }], examples: [{ sentence: 'Minha família é unida.', translation: 'My family is close.' }], topicTags: ['family'] },

  // ── Chinese (zh) ──
  { word: '你好', languageCode: 'zh', cefrLevel: 'A1', partOfSpeech: 'interjection', transliteration: 'nǐ hǎo', definitions: [{ meaning: 'used as a greeting' }], examples: [{ sentence: '你好，你怎么样？', translation: 'Hello, how are you?' }], topicTags: ['greetings'] },
  { word: '谢谢', languageCode: 'zh', cefrLevel: 'A1', partOfSpeech: 'interjection', transliteration: 'xiè xiè', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: '谢谢你的帮助。', translation: 'Thank you for your help.' }], topicTags: ['politeness'] },
  { word: '水', languageCode: 'zh', cefrLevel: 'A1', partOfSpeech: 'noun', transliteration: 'shuǐ', definitions: [{ meaning: 'clear liquid needed for life' }], examples: [{ sentence: '请给我一杯水。', translation: 'Please give me a glass of water.' }], topicTags: ['food'] },
  { word: '家', languageCode: 'zh', cefrLevel: 'A1', partOfSpeech: 'noun', transliteration: 'jiā', definitions: [{ meaning: 'home or family' }], examples: [{ sentence: '我的家很大。', translation: 'My home is big.' }], topicTags: ['home'] },
  { word: '吃', languageCode: 'zh', cefrLevel: 'A1', partOfSpeech: 'verb', transliteration: 'chī', definitions: [{ meaning: 'to eat' }], examples: [{ sentence: '我早上七点吃早饭。', translation: 'I eat breakfast at 7am.' }], topicTags: ['food'] },
  { word: '工作', languageCode: 'zh', cefrLevel: 'A2', partOfSpeech: 'verb', transliteration: 'gōng zuò', definitions: [{ meaning: 'to work' }], examples: [{ sentence: '我在办公室工作。', translation: 'I work in an office.' }], topicTags: ['work'] },
  { word: '快乐', languageCode: 'zh', cefrLevel: 'A1', partOfSpeech: 'adjective', transliteration: 'kuài lè', definitions: [{ meaning: 'happy' }], examples: [{ sentence: '我很快乐。', translation: 'I am very happy.' }], topicTags: ['emotions'] },
  { word: '大', languageCode: 'zh', cefrLevel: 'A1', partOfSpeech: 'adjective', transliteration: 'dà', definitions: [{ meaning: 'big' }], examples: [{ sentence: '那只狗很大。', translation: 'That dog is big.' }], topicTags: ['descriptions'] },

  // ── Japanese (ja) ──
  { word: 'こんにちは', languageCode: 'ja', cefrLevel: 'A1', partOfSpeech: 'interjection', transliteration: 'konnichiwa', definitions: [{ meaning: 'used as a daytime greeting' }], examples: [{ sentence: 'こんにちは、元気ですか？', translation: 'Hello, how are you?' }], topicTags: ['greetings'] },
  { word: 'ありがとう', languageCode: 'ja', cefrLevel: 'A1', partOfSpeech: 'interjection', transliteration: 'arigatō', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: 'ありがとうございます。', translation: 'Thank you very much.' }], topicTags: ['politeness'] },
  { word: '水', languageCode: 'ja', cefrLevel: 'A1', partOfSpeech: 'noun', transliteration: 'mizu', definitions: [{ meaning: 'water' }], examples: [{ sentence: '水をください。', translation: 'Water, please.' }], topicTags: ['food'] },
  { word: '家', languageCode: 'ja', cefrLevel: 'A1', partOfSpeech: 'noun', transliteration: 'ie', definitions: [{ meaning: 'house or home' }], examples: [{ sentence: '私の家は小さいです。', translation: 'My house is small.' }], topicTags: ['home'] },
  { word: '食べる', languageCode: 'ja', cefrLevel: 'A1', partOfSpeech: 'verb', transliteration: 'taberu', definitions: [{ meaning: 'to eat' }], examples: [{ sentence: '朝ごはんを食べます。', translation: 'I eat breakfast.' }], topicTags: ['food'] },
  { word: '仕事', languageCode: 'ja', cefrLevel: 'A2', partOfSpeech: 'noun', transliteration: 'shigoto', definitions: [{ meaning: 'work or job' }], examples: [{ sentence: '私は仕事を探しています。', translation: 'I am looking for work.' }], topicTags: ['work'] },
  { word: '大きい', languageCode: 'ja', cefrLevel: 'A1', partOfSpeech: 'adjective', transliteration: 'ōkii', definitions: [{ meaning: 'big' }], examples: [{ sentence: 'あの犬は大きいです。', translation: 'That dog is big.' }], topicTags: ['descriptions'] },
  { word: '嬉しい', languageCode: 'ja', cefrLevel: 'A1', partOfSpeech: 'adjective', transliteration: 'ureshii', definitions: [{ meaning: 'happy' }], examples: [{ sentence: 'あなたに会えて嬉しいです。', translation: 'I am happy to see you.' }], topicTags: ['emotions'] },

  // ── Korean (ko) ──
  { word: '안녕하세요', languageCode: 'ko', cefrLevel: 'A1', partOfSpeech: 'interjection', transliteration: 'annyeonghaseyo', definitions: [{ meaning: 'used as a greeting' }], examples: [{ sentence: '안녕하세요, 어떻게 지내세요?', translation: 'Hello, how are you?' }], topicTags: ['greetings'] },
  { word: '감사합니다', languageCode: 'ko', cefrLevel: 'A1', partOfSpeech: 'interjection', transliteration: 'gamsahamnida', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: '도와주셔서 감사합니다.', translation: 'Thank you for helping me.' }], topicTags: ['politeness'] },
  { word: '물', languageCode: 'ko', cefrLevel: 'A1', partOfSpeech: 'noun', transliteration: 'mul', definitions: [{ meaning: 'water' }], examples: [{ sentence: '물 한 잔 주세요.', translation: 'Please give me a glass of water.' }], topicTags: ['food'] },
  { word: '집', languageCode: 'ko', cefrLevel: 'A1', partOfSpeech: 'noun', transliteration: 'jip', definitions: [{ meaning: 'house' }], examples: [{ sentence: '우리 집은 작아요.', translation: 'My house is small.' }], topicTags: ['home'] },
  { word: '먹다', languageCode: 'ko', cefrLevel: 'A1', partOfSpeech: 'verb', transliteration: 'meokda', definitions: [{ meaning: 'to eat' }], examples: [{ sentence: '아침을 먹어요.', translation: 'I eat breakfast.' }], topicTags: ['food'] },
  { word: '행복하다', languageCode: 'ko', cefrLevel: 'A1', partOfSpeech: 'adjective', transliteration: 'haengbokada', definitions: [{ meaning: 'to be happy' }], examples: [{ sentence: '당신을 만나서 행복해요.', translation: 'I am happy to meet you.' }], topicTags: ['emotions'] },
  { word: '일하다', languageCode: 'ko', cefrLevel: 'A2', partOfSpeech: 'verb', transliteration: 'ilhada', definitions: [{ meaning: 'to work' }], examples: [{ sentence: '저는 사무실에서 일해요.', translation: 'I work in an office.' }], topicTags: ['work'] },
  { word: '크다', languageCode: 'ko', cefrLevel: 'A1', partOfSpeech: 'adjective', transliteration: 'keuda', definitions: [{ meaning: 'big' }], examples: [{ sentence: '그 개는 커요.', translation: 'That dog is big.' }], topicTags: ['descriptions'] },

  // ── Russian (ru) ──
  { word: 'здравствуйте', languageCode: 'ru', cefrLevel: 'A1', partOfSpeech: 'interjection', transliteration: 'zdravstvuyte', definitions: [{ meaning: 'used as a formal greeting' }], examples: [{ sentence: 'Здравствуйте, как дела?', translation: 'Hello, how are you?' }], topicTags: ['greetings'] },
  { word: 'спасибо', languageCode: 'ru', cefrLevel: 'A1', partOfSpeech: 'interjection', transliteration: 'spasibo', definitions: [{ meaning: 'express gratitude' }], examples: [{ sentence: 'Спасибо за помощь.', translation: 'Thank you for your help.' }], topicTags: ['politeness'] },
  { word: 'вода', languageCode: 'ru', cefrLevel: 'A1', partOfSpeech: 'noun', transliteration: 'voda', definitions: [{ meaning: 'water' }], examples: [{ sentence: 'Дайте воды, пожалуйста.', translation: 'Give water, please.' }], topicTags: ['food'] },
  { word: 'дом', languageCode: 'ru', cefrLevel: 'A1', partOfSpeech: 'noun', transliteration: 'dom', definitions: [{ meaning: 'house or home' }], examples: [{ sentence: 'Мой дом большой.', translation: 'My house is big.' }], topicTags: ['home'] },
  { word: 'есть', languageCode: 'ru', cefrLevel: 'A1', partOfSpeech: 'verb', transliteration: 'yest\'', definitions: [{ meaning: 'to eat' }], examples: [{ sentence: 'Я ем в семь утра.', translation: 'I eat at 7am.' }], topicTags: ['food'] },
  { word: 'работа', languageCode: 'ru', cefrLevel: 'A2', partOfSpeech: 'noun', transliteration: 'rabota', definitions: [{ meaning: 'work or job' }], examples: [{ sentence: 'Я ищу работу.', translation: 'I am looking for work.' }], topicTags: ['work'] },
  { word: 'большой', languageCode: 'ru', cefrLevel: 'A1', partOfSpeech: 'adjective', transliteration: 'bol\'shoy', definitions: [{ meaning: 'big' }], examples: [{ sentence: 'Это большой дом.', translation: 'This is a big house.' }], topicTags: ['descriptions'] },
  { word: 'счастливый', languageCode: 'ru', cefrLevel: 'A1', partOfSpeech: 'adjective', transliteration: 'schastlivyy', definitions: [{ meaning: 'happy' }], examples: [{ sentence: 'Я счастлив тебя видеть.', translation: 'I am happy to see you.' }], topicTags: ['emotions'] },
];

const GRAMMAR_LESSONS = [
  // ── English ──
  { languageCode: 'en', cefrLevel: 'A1', title: 'Present Simple: To Be', grammarPoint: 'present-simple-to-be', explanation: 'The verb "to be" (am/is/are) is used to describe states, identities, and characteristics. It changes form depending on the subject.', shortExplanation: '"am" for I, "is" for he/she/it, "are" for you/we/they', difficulty: 1, examples: [{ sentence: 'I am a student.', translation: '' }, { sentence: 'She is happy.', translation: '' }, { sentence: 'They are from Spain.', translation: '' }], rules: ['Use "am" with I', 'Use "is" with he/she/it', 'Use "are" with you/we/they', 'For negatives, add "not" after the verb'], exceptions: [], commonMistakes: [{ mistake: 'He are happy', correct: 'He is happy' }, { mistake: 'I is a teacher', correct: 'I am a teacher' }], relatedLessons: ['present-simple-other-verbs', 'subject-pronouns'] },
  { languageCode: 'en', cefrLevel: 'A1', title: 'Present Simple: Other Verbs', grammarPoint: 'present-simple-other-verbs', explanation: 'Use the base form of the verb for I/you/we/they. Add -s or -es for he/she/it.', shortExplanation: 'Add -s/-es for third person singular', difficulty: 1, examples: [{ sentence: 'I eat breakfast at 7am.', translation: '' }, { sentence: 'She eats lunch at noon.', translation: '' }, { sentence: 'They live in London.', translation: '' }], rules: ['Add -s for most verbs with he/she/it', 'Add -es for verbs ending in -ch, -sh, -s, -x, -o', 'Change -y to -ies for verbs ending in consonant + y'], exceptions: ['have becomes has', 'go becomes goes', 'do becomes does'], commonMistakes: [{ mistake: 'He eat breakfast', correct: 'He eats breakfast' }, { mistake: 'She go to school', correct: 'She goes to school' }], relatedLessons: ['present-simple-to-be', 'subject-pronouns'] },
  { languageCode: 'en', cefrLevel: 'A1', title: 'Subject Pronouns', grammarPoint: 'subject-pronouns', explanation: 'Subject pronouns replace the subject of a sentence. They tell us who is doing the action.', shortExplanation: 'I, you, he, she, it, we, they', difficulty: 1, examples: [{ sentence: 'She is a doctor.', translation: '' }, { sentence: 'We live in New York.', translation: '' }, { sentence: 'It is raining.', translation: '' }], rules: ['Use "I" for yourself', 'Use "you" for the person you are talking to', 'Use "he" for a man, "she" for a woman', 'Use "it" for things or animals', 'Use "we" for yourself and others', 'Use "they" for other people or things'], exceptions: [], commonMistakes: [{ mistake: 'Me am happy', correct: 'I am happy' }, { mistake: 'Her is nice', correct: 'She is nice' }], relatedLessons: ['present-simple-to-be', 'object-pronouns'] },
  { languageCode: 'en', cefrLevel: 'A1', title: 'Articles: A/An/The', grammarPoint: 'articles-a-an-the', explanation: 'Articles come before nouns. "A" and "an" are indefinite articles. "The" is the definite article.', shortExplanation: 'a/an = any one; the = specific one', difficulty: 1, examples: [{ sentence: 'I saw a dog in the park.', translation: '' }, { sentence: 'She is an engineer.', translation: '' }, { sentence: 'The book on the table is mine.', translation: '' }], rules: ['Use "a" before consonant sounds: a cat, a house', 'Use "an" before vowel sounds: an apple, an hour', 'Use "the" when both speaker and listener know which one', 'Use "the" for unique things: the sun, the moon'], exceptions: ['University starts with "u" but sounds like consonant → a university', 'Hour starts with "h" but sounds like vowel → an hour'], commonMistakes: [{ mistake: 'I have a apple', correct: 'I have an apple' }, { mistake: 'She is the teacher (when unspecified)', correct: 'She is a teacher' }], relatedLessons: ['nouns-countable-uncountable', 'plural-nouns'] },
  { languageCode: 'en', cefrLevel: 'A1', title: 'Plural Nouns', grammarPoint: 'plural-nouns', explanation: 'Regular plurals add -s or -es. Some nouns have irregular plural forms.', shortExplanation: 'Add -s for most nouns', difficulty: 1, examples: [{ sentence: 'I have two cats.', translation: '' }, { sentence: 'There are three boxes.', translation: '' }, { sentence: 'The children are playing.', translation: '' }], rules: ['Add -s to most nouns: cat → cats', 'Add -es to nouns ending in -ch, -sh, -s, -x, -o: box → boxes', 'Change -y to -ies: baby → babies', 'Change -f/-fe to -ves: leaf → leaves'], exceptions: ['child → children', 'man → men', 'woman → women', 'foot → feet', 'tooth → teeth', 'mouse → mice', 'sheep → sheep', 'fish → fish'], commonMistakes: [{ mistake: 'Two childs', correct: 'Two children' }, { mistake: 'Three mouses', correct: 'Three mice' }], relatedLessons: ['articles-a-an-the', 'nouns-countable-uncountable'] },
  { languageCode: 'en', cefrLevel: 'A1', title: 'Possessive Adjectives', grammarPoint: 'possessive-adjectives', explanation: 'Possessive adjectives show ownership. They come before a noun.', shortExplanation: 'my, your, his, her, its, our, their', difficulty: 1, examples: [{ sentence: 'This is my book.', translation: '' }, { sentence: 'Her name is Maria.', translation: '' }, { sentence: 'Our house is big.', translation: '' }], rules: ['Use "my" for yourself', 'Use "your" for the person you are talking to', 'Use "his" for a man, "her" for a woman', 'Use "its" for things or animals', 'Use "our" for yourself and others', 'Use "their" for other people'], exceptions: ['Its has no apostrophe (its vs it\'s)'], commonMistakes: [{ mistake: 'She lost her keys' }, { mistake: 'Its a nice day (should be it\'s)', correct: 'It\'s a nice day' }], relatedLessons: ['subject-pronouns', 'possessive-pronouns'] },
  { languageCode: 'en', cefrLevel: 'A2', title: 'Past Simple: Regular Verbs', grammarPoint: 'past-simple-regular', explanation: 'The past simple is used for completed actions in the past. Regular verbs add -ed.', shortExplanation: 'Add -ed for past tense', difficulty: 2, examples: [{ sentence: 'I walked to school yesterday.', translation: '' }, { sentence: 'She studied all night.', translation: '' }, { sentence: 'They played football last weekend.', translation: '' }], rules: ['Add -ed to most verbs: walk → walked', 'Add -d to verbs ending in -e: love → loved', 'Change -y to -ied: study → studied', 'Double the final consonant: stop → stopped'], exceptions: ['Some verbs ending in -y change to -ied: carry → carried'], commonMistakes: [{ mistake: 'I walk to school yesterday', correct: 'I walked to school yesterday' }, { mistake: 'She studyed hard', correct: 'She studied hard' }], relatedLessons: ['past-simple-irregular', 'past-simple-to-be'] },
  { languageCode: 'en', cefrLevel: 'A2', title: 'Past Simple: Irregular Verbs', grammarPoint: 'past-simple-irregular', explanation: 'Many common verbs have irregular past forms. These must be memorized.', shortExplanation: 'Irregular past forms must be learned individually', difficulty: 2, examples: [{ sentence: 'I went to Paris last year.', translation: '' }, { sentence: 'She ate lunch at noon.', translation: '' }, { sentence: 'They had a great time.', translation: '' }], rules: ['Irregular verbs do not follow a pattern', 'The past form is the same for all subjects', 'Common irregular verbs: go→went, eat→ate, have→had, see→saw, do→did'], exceptions: [], commonMistakes: [{ mistake: 'I goed to the store', correct: 'I went to the store' }, { mistake: 'She eated dinner', correct: 'She ate dinner' }], relatedLessons: ['past-simple-regular', 'present-perfect'] },
  { languageCode: 'en', cefrLevel: 'A2', title: 'Present Continuous', grammarPoint: 'present-continuous', explanation: 'Present continuous describes actions happening now or around now. Form: am/is/are + verb-ing.', shortExplanation: 'am/is/are + verb-ing for actions now', difficulty: 2, examples: [{ sentence: 'I am reading a book right now.', translation: '' }, { sentence: 'She is studying for her exam.', translation: '' }, { sentence: 'They are playing outside.', translation: '' }], rules: ['Use "am" with I, "is" with he/she/it, "are" with you/we/they', 'Add -ing to the main verb', 'For verbs ending in -e, remove -e and add -ing: make → making', 'For CVC verbs, double the last letter: run → running'], exceptions: ['Stative verbs (know, believe, love) are not usually used in continuous form'], commonMistakes: [{ mistake: 'I am know the answer', correct: 'I know the answer' }, { mistake: 'She is makeing dinner', correct: 'She is making dinner' }], relatedLessons: ['present-simple-other-verbs', 'stative-verbs'] },
  { languageCode: 'en', cefrLevel: 'A2', title: 'Comparatives and Superlatives', grammarPoint: 'comparatives-superlatives', explanation: 'Comparatives compare two things. Superlatives compare three or more.', shortExplanation: '-er/-est for short adjectives, more/most for long ones', difficulty: 2, examples: [{ sentence: 'She is taller than her brother.', translation: '' }, { sentence: 'This is the most expensive hotel.', translation: '' }, { sentence: 'He is better at math than me.', translation: '' }], rules: ['Add -er for short adjectives (1-2 syllables): tall → taller', 'Add -est for short adjectives: tall → tallest', 'Use more/most for long adjectives: beautiful → more beautiful', 'Use "than" after comparatives', 'Use "the" before superlatives'], exceptions: ['good → better → best', 'bad → worse → worst', 'far → farther/further → farthest/furthest'], commonMistakes: [{ mistake: 'She is more taller than me', correct: 'She is taller than me' }, { mistake: 'This is the most best', correct: 'This is the best' }], relatedLessons: ['adjectives-basic', 'adverbs-comparison'] },
  { languageCode: 'en', cefrLevel: 'A2', title: 'Future with Going To', grammarPoint: 'future-going-to', explanation: '"Going to" expresses planned future actions or predictions based on evidence.', shortExplanation: 'am/is/are + going to + verb', difficulty: 2, examples: [{ sentence: 'I am going to visit my grandmother tomorrow.', translation: '' }, { sentence: 'It is going to rain. Look at those clouds!', translation: '' }, { sentence: 'They are going to buy a new car.', translation: '' }], rules: ['Use am/is/are + going to + base verb', 'Use for planned actions', 'Use for predictions with evidence'], exceptions: ['For spontaneous decisions, use "will" instead'], commonMistakes: [{ mistake: 'I going to travel (missing am)', correct: 'I am going to travel' }, { mistake: 'She is go to study', correct: 'She is going to study' }], relatedLessons: ['future-will', 'present-continuous-future'] },
  { languageCode: 'en', cefrLevel: 'B1', title: 'Present Perfect Simple', grammarPoint: 'present-perfect', explanation: 'Present perfect connects past actions to the present. Form: have/has + past participle.', shortExplanation: 'have/has + past participle', difficulty: 3, examples: [{ sentence: 'I have visited Paris three times.', translation: '' }, { sentence: 'She has never tried sushi.', translation: '' }, { sentence: 'They have already finished their homework.', translation: '' }], rules: ['Use have with I/you/we/they, has with he/she/it', 'Past participle: regular = -ed, irregular = 3rd column', 'Use for life experiences, recent changes, unfinished time periods'], exceptions: ['Cannot use with specific past time expressions (yesterday, last year)'], commonMistakes: [{ mistake: 'I have gone to Paris yesterday', correct: 'I went to Paris yesterday' }, { mistake: 'She has went home', correct: 'She has gone home' }], relatedLessons: ['past-simple-irregular', 'present-perfect-continuous'] },
  { languageCode: 'en', cefrLevel: 'B1', title: 'First Conditional', grammarPoint: 'first-conditional', explanation: 'First conditional describes real/possible future situations. If + present simple, will + base verb.', shortExplanation: 'If + present, will + base verb (real future)', difficulty: 3, examples: [{ sentence: 'If it rains, I will take an umbrella.', translation: '' }, { sentence: 'She will pass if she studies hard.', translation: '' }, { sentence: 'If you are tired, go to bed.', translation: '' }], rules: ['The if-clause uses present simple', 'The result clause uses will + base verb', 'The if-clause can come first or second', 'No comma needed when if-clause is second'], exceptions: ['Can use modals (can, might, should) in the result clause'], commonMistakes: [{ mistake: 'If it will rain, I will stay home', correct: 'If it rains, I will stay home' }, { mistake: 'I will go if I will have time', correct: 'I will go if I have time' }], relatedLessons: ['second-conditional', 'future-will'] },
  { languageCode: 'en', cefrLevel: 'B1', title: 'Second Conditional', grammarPoint: 'second-conditional', explanation: 'Second conditional describes unreal/hypothetical present or future situations. If + past simple, would + base verb.', shortExplanation: 'If + past, would + base verb (unreal situations)', difficulty: 3, examples: [{ sentence: 'If I won the lottery, I would travel the world.', translation: '' }, { sentence: 'She would buy a house if she had more money.', translation: '' }, { sentence: 'If I were you, I would accept the offer.', translation: '' }], rules: ['The if-clause uses past simple', 'The result clause uses would + base verb', 'Use "were" for all subjects in the if-clause (were was)', 'Describes unreal or improbable situations'], exceptions: ['"If I were" is used for all subjects (not "if I was")'], commonMistakes: [{ mistake: 'If I would win, I would buy a car', correct: 'If I won, I would buy a car' }, { mistake: 'If I was you', correct: 'If I were you' }], relatedLessons: ['first-conditional', 'third-conditional'] },
  { languageCode: 'en', cefrLevel: 'B1', title: 'Passive Voice', grammarPoint: 'passive-voice', explanation: 'Passive voice emphasizes the action or the receiver of the action, not the doer. Form: be + past participle.', shortExplanation: 'be + past participle', difficulty: 3, examples: [{ sentence: 'The book was written by J.K. Rowling.', translation: '' }, { sentence: 'English is spoken worldwide.', translation: '' }, { sentence: 'The window was broken last night.', translation: '' }], rules: ['The object of the active sentence becomes the subject', 'Use the correct tense of "be" + past participle', 'Use "by" to mention the doer (optional)'], exceptions: ['Some verbs (have, fit, suit) are rarely used in passive'], commonMistakes: [{ mistake: 'The book was wrote by her', correct: 'The book was written by her' }, { mistake: 'It is being use', correct: 'It is being used' }], relatedLessons: ['present-perfect', 'past-simple-irregular'] },
  { languageCode: 'en', cefrLevel: 'B1', title: 'Relative Clauses', grammarPoint: 'relative-clauses', explanation: 'Relative clauses give more information about a noun. They start with who, which, that, whose, or where.', shortExplanation: 'who/which/that/whose/where give extra information', difficulty: 3, examples: [{ sentence: 'The woman who lives next door is a doctor.', translation: '' }, { sentence: 'This is the book that I told you about.', translation: '' }, { sentence: 'The restaurant where we ate was excellent.', translation: '' }], rules: ['Use "who" for people', 'Use "which" for things', 'Use "that" for people or things (in defining clauses)', 'Use "where" for places', 'Use "whose" for possession'], exceptions: ['In non-defining clauses (with commas), use who/which but not that'], commonMistakes: [{ mistake: 'The man which called you' , correct: 'The man who called you' }, { mistake: 'This is the house who I live in', correct: 'This is the house where I live' }], relatedLessons: ['relative-pronouns', 'defining-vs-non-defining'] },

  // ── Spanish ──
  { languageCode: 'es', cefrLevel: 'A1', title: 'Presente de Indicativo: Verbos Regulares (-AR)', grammarPoint: 'presente-regular-ar', explanation: 'Los verbos regulares que terminan en -AR siguen un patrón fijo en presente.', shortExplanation: '-o, -as, -a, -amos, -áis, -an', difficulty: 1, examples: [{ sentence: 'Yo hablo español.', translation: 'I speak Spanish.' }, { sentence: 'Tú cantas muy bien.', translation: 'You sing very well.' }], rules: ['Eliminar -AR y añadir: -o, -as, -a, -amos, -áis, -an'], exceptions: [], commonMistakes: [{ mistake: 'Yo hablo español', correct: 'Yo hablo español' }], relatedLessons: ['presente-regular-er', 'presente-regular-ir'] },
  { languageCode: 'es', cefrLevel: 'A1', title: 'Género de los Sustantivos', grammarPoint: 'genero-sustantivos', explanation: 'En español, los sustantivos tienen género: masculino o femenino.', shortExplanation: '-o = masculino, -a = femenino', difficulty: 1, examples: [{ sentence: 'El libro es interesante.', translation: 'The book is interesting.' }, { sentence: 'La casa es blanca.', translation: 'The house is white.' }], rules: ['Los sustantivos que terminan en -o generalmente son masculinos', 'Los que terminan en -a generalmente son femeninos', 'El artículo debe concordar con el género'], exceptions: ['El día (masculino a pesar de -a)', 'La mano (femenino a pesar de -o)', 'El agua (femenino pero usa "el" por fonética)'], commonMistakes: [{ mistake: 'La problema', correct: 'El problema' }], relatedLessons: ['articulos-determinados', 'concordancia'] },
  { languageCode: 'es', cefrLevel: 'A2', title: 'Pretérito Perfecto', grammarPoint: 'preterito-perfecto', explanation: 'El pretérito perfecto expresa acciones pasadas que tienen relevancia en el presente.', shortExplanation: 'haber + participio (-ado/-ido)', difficulty: 2, examples: [{ sentence: 'He comido paella hoy.', translation: 'I have eaten paella today.' }, { sentence: '¿Has visto esa película?', translation: 'Have you seen that movie?' }], rules: ['Usar el presente de haber (he, has, ha, hemos, habéis, han) + participio', 'Participios regulares: -AR → -ado, -ER/-IR → -ido'], exceptions: ['Participios irregulares: abrir → abierto, hacer → hecho, decir → dicho, ver → visto', 'Escribir → escrito'], commonMistakes: [{ mistake: 'He comido ayer', correct: 'Comí ayer' }], relatedLessons: ['preterito-indefinido', 'participios-irregulares'] },
  { languageCode: 'es', cefrLevel: 'B1', title: 'Subjuntivo Presente', grammarPoint: 'subjuntivo-presente', explanation: 'El subjuntivo expresa deseos, dudas, emociones y situaciones hipotéticas.', shortExplanation: 'Forma especial del verbo para expresar subjetividad', difficulty: 3, examples: [{ sentence: 'Espero que tengas un buen día.', translation: 'I hope you have a good day.' }, { sentence: 'Dudo que él venga.', translation: 'I doubt he will come.' }], rules: ['Para verbos -AR: -e, -es, -e, -emos, -éis, -en', 'Para verbos -ER/-IR: -a, -as, -a, -amos, -áis, -an', 'Se usa después de "que" con expresiones de emoción, duda, deseo'], exceptions: ['Muchos verbos tienen irregularidades en subjuntivo'], commonMistakes: [{ mistake: 'Espero que tu vienes', correct: 'Espero que tú vengas' }], relatedLessons: ['indicativo-vs-subjuntivo', 'subjuntivo-imperfecto'] },
  { languageCode: 'es', cefrLevel: 'A2', title: 'Ser vs Estar', grammarPoint: 'ser-vs-estar', explanation: 'Ser y Estar ambos significan "to be" pero se usan en contextos diferentes.', shortExplanation: 'Ser = permanente, Estar = temporal', difficulty: 2, examples: [{ sentence: 'Soy de México.', translation: 'I am from Mexico.' }, { sentence: 'Estoy cansado.', translation: 'I am tired.' }], rules: ['Ser: identidad, origen, profesión, características permanentes, hora, fecha', 'Estar: estado temporal, ubicación, emociones, condiciones físicas'], exceptions: ['La ubicación de eventos usa ser: "La fiesta es en mi casa"'], commonMistakes: [{ mistake: 'Estoy médico', correct: 'Soy médico' }, { mistake: 'Soy en casa', correct: 'Estoy en casa' }], relatedLessons: ['presente-regular-ar', 'adjetivos-basicos'] },

  // ── French ──
  { languageCode: 'fr', cefrLevel: 'A1', title: 'Être et Avoir au Présent', grammarPoint: 'etre-avoir-present', explanation: 'Les verbes être et avoir sont les verbes les plus importants en français.', shortExplanation: 'Être: suis/es/est/sommes/êtes/sont — Avoir: ai/as/a/avons/avez/ont', difficulty: 1, examples: [{ sentence: 'Je suis français.', translation: 'I am French.' }, { sentence: 'Elle a un chat.', translation: 'She has a cat.' }], rules: ['Être: je suis, tu es, il/elle/on est, nous sommes, vous êtes, ils/elles sont', 'Avoir: j\'ai, tu as, il/elle/on a, nous avons, vous avez, ils/elles ont'], exceptions: [], commonMistakes: [{ mistake: 'Je avoir faim', correct: 'J\'ai faim' }], relatedLessons: ['present-regular-er', 'articles-definis'] },
  { languageCode: 'fr', cefrLevel: 'A1', title: 'Articles Définis et Indéfinis', grammarPoint: 'articles-francais', explanation: 'Les articles s\'accordent en genre et en nombre avec le nom.', shortExplanation: 'le/la/les = the, un/une/des = a/some', difficulty: 1, examples: [{ sentence: 'Le livre est sur la table.', translation: 'The book is on the table.' }, { sentence: 'C\'est une bonne idée.', translation: 'That is a good idea.' }], rules: ['Définis: le (masculin), la (féminin), les (pluriel)', 'Indéfinis: un (masculin), une (féminin), des (pluriel)', 'Devant une voyelle: l\''], exceptions: ['Le/la deviennent l\' devant une voyelle ou h muet'], commonMistakes: [{ mistake: 'Le eau (should be l\'eau)', correct: 'L\'eau' }], relatedLessons: ['etre-avoir-present', 'genre-noms'] },
  { languageCode: 'fr', cefrLevel: 'A2', title: 'Passé Composé', grammarPoint: 'passe-compose', explanation: 'Le passé composé exprime une action passée terminée. Il se forme avec l\'auxiliaire + participe passé.', shortExplanation: 'avoir/être + participe passé', difficulty: 2, examples: [{ sentence: 'J\'ai mangé une pomme.', translation: 'I ate an apple.' }, { sentence: 'Elle est allée au marché.', translation: 'She went to the market.' }], rules: ['La plupart des verbes utilisent avoir + participe passé', '16 verbes (venir, aller, naître, etc.) utilisent être', 'Avec être, le participe s\'accorde avec le sujet'], exceptions: ['Les verbes pronominaux (se lever, se laver) utilisent toujours être'], commonMistakes: [{ mistake: 'J\'ai allé', correct: 'Je suis allé' }], relatedLessons: ['etre-avoir-present', 'participes-passes'] },
  { languageCode: 'fr', cefrLevel: 'B1', title: 'Subjonctif Présent', grammarPoint: 'subjonctif-francais', explanation: 'Le subjonctif exprime le doute, l\'émotion, la nécessité ou l\'incertitude.', shortExplanation: 'Forme verbale employée après certaines expressions', difficulty: 3, examples: [{ sentence: 'Il faut que tu viennes.', translation: 'You must come.' }, { sentence: 'Je doute qu\'il ait raison.', translation: 'I doubt he is right.' }], rules: ['Se forme à partir de la 3e personne du pluriel du présent', 'Terminaisons: -e, -es, -e, -ions, -iez, -ent', 'S\'emploie après: il faut que, bien que, pour que, avant que'], exceptions: ['Les verbes être et avoir ont des racines irrégulières au subjonctif'], commonMistakes: [{ mistake: 'Il faut que tu viens', correct: 'Il faut que tu viennes' }], relatedLessons: ['indicatif-vs-subjonctif', 'passe-compose'] },
  { languageCode: 'fr', cefrLevel: 'A2', title: 'Futur Proche', grammarPoint: 'futur-proche', explanation: 'Le futur proche exprime une action qui va bientôt se produire.', shortExplanation: 'aller + infinitif', difficulty: 2, examples: [{ sentence: 'Je vais étudier ce soir.', translation: 'I am going to study tonight.' }, { sentence: 'Nous allons voyager en France.', translation: 'We are going to travel to France.' }], rules: ['Utiliser le présent du verbe aller + l\'infinitif', 'Très utilisé dans la langue parlée'], exceptions: [], commonMistakes: [{ mistake: 'Je vais étudier hier (cannot use for past)', correct: 'J\'ai étudié hier' }], relatedLessons: ['etre-avoir-present', 'futur-simple'] },

  // ── German ──
  { languageCode: 'de', cefrLevel: 'A1', title: 'Verben im Präsens', grammarPoint: 'verben-prasens', explanation: 'Deutsche Verben ändern ihre Endung je nach Subjekt (ich, du, er/sie/es, wir, ihr, sie/Sie).', shortExplanation: 'Stamm + Endung (-e, -st, -t, -en, -t, -en)', difficulty: 1, examples: [{ sentence: 'Ich wohne in Berlin.', translation: 'I live in Berlin.' }, { sentence: 'Er spielt Fußball.', translation: 'He plays soccer.' }], rules: ['Stamm + Endung: ich -e, du -st, er/sie/es -t, wir -en, ihr -t, sie/Sie -en'], exceptions: ['Bei Stamm endet auf -d/-t: du findest, er findet', 'Bei Stamm endet auf -s/-ß/-z: du heißt, er heißt'], commonMistakes: [{ mistake: 'Ich spielen Fußball', correct: 'Ich spiele Fußball' }], relatedLessons: ['sein-haben', 'trennbare-verben'] },
  { languageCode: 'de', cefrLevel: 'A1', title: 'Bestimmte und Unbestimmte Artikel', grammarPoint: 'artikel-deutsch', explanation: 'Deutsche Artikel zeigen Genus (maskulin, feminin, neutrum) und Kasus (Nominativ, Akkusativ, Dativ, Genitiv).', shortExplanation: 'der/die/das = the, ein/eine = a/an', difficulty: 1, examples: [{ sentence: 'Der Mann ist mein Vater.', translation: 'The man is my father.' }, { sentence: 'Ich habe eine Katze.', translation: 'I have a cat.' }], rules: ['Nominativ: der (m), die (f), das (n), die (pl)', 'Akkusativ: den (m), die (f), das (n), die (pl)', 'Dativ: dem (m), der (f), dem (n), den + -n (pl)'], exceptions: [], commonMistakes: [{ mistake: 'Ich sehe der Mann (should be Akkusativ)', correct: 'Ich sehe den Mann' }], relatedLessons: ['verben-prasens', 'plural-nomen'] },
  { languageCode: 'de', cefrLevel: 'A2', title: 'Perfekt mit haben und sein', grammarPoint: 'perfekt-deutsch', explanation: 'Das Perfekt wird für abgeschlossene Handlungen in der Vergangenheit verwendet.', shortExplanation: 'haben/sein + Partizip II', difficulty: 2, examples: [{ sentence: 'Ich habe gegessen.', translation: 'I have eaten.' }, { sentence: 'Sie ist nach Hause gegangen.', translation: 'She went home.' }], rules: ['Die meisten Verben bilden das Perfekt mit haben', 'Verben der Bewegung/des Zustandswechsels bilden es mit sein'], exceptions: ['Die Partizipformen müssen gelernt werden: gehen → gegangen, fahren → gefahren'], commonMistakes: [{ mistake: 'Ich habe gegangen', correct: 'Ich bin gegangen' }], relatedLessons: ['verben-prasens', 'partizip-II'] },
  { languageCode: 'de', cefrLevel: 'B1', title: 'Nebensätze mit dass, weil, obwohl', grammarPoint: 'nebensatze', explanation: 'Nebensätze mit Konjunktionen wie dass, weil, obwohl haben eine besondere Wortstellung: das Verb kommt ans Ende.', shortExplanation: 'Verb am Ende des Nebensatzes', difficulty: 3, examples: [{ sentence: 'Ich glaube, dass er kommt.', translation: 'I believe that he is coming.' }, { sentence: 'Er ist müde, weil er wenig geschlafen hat.', translation: 'He is tired because he slept little.' }], rules: ['Konjunktionen (dass, weil, obwohl) leiten den Nebensatz ein', 'Das konjugierte Verb steht am Ende des Nebensatzes', 'Bei zusammengesetzten Zeiten kommt das Hilfsverb ans Ende'], exceptions: ['Trotzdem, dann, aber sind keine Nebensatzkonjunktionen'], commonMistakes: [{ mistake: 'Weil ich bin müde', correct: 'Weil ich müde bin' }], relatedLessons: ['hauptsatz-nebensatz', 'konjunktionen'] },
  { languageCode: 'de', cefrLevel: 'A2', title: 'Trennbare Verben', grammarPoint: 'trennbare-verben', explanation: 'Trennbare Verben bestehen aus einem Präfix und einem Basisverb. Im Präsens wird das Präfix abgetrennt und ans Ende gestellt.', shortExplanation: 'Präfix + Verb, Präfix geht ans Ende', difficulty: 2, examples: [{ sentence: 'Ich stehe um 7 Uhr auf.', translation: 'I get up at 7am.' }, { sentence: 'Er macht das Licht an.', translation: 'He turns on the light.' }], rules: ['Präfix (auf-, an-, ein-, aus-, mit-, etc.) + Basisverb', 'Im Präsens: konjugiertes Verb an Position 2, Präfix ans Ende'], exceptions: ['Bei untrennbaren Verben (be-, ge-, er-, ver-, zer-) bleibt das Präfix'], commonMistakes: [{ mistake: 'Ich aufstehe um 7 Uhr', correct: 'Ich stehe um 7 Uhr auf' }], relatedLessons: ['verben-prasens', 'perfekt-deutsch'] },

  // ── Italian ──
  { languageCode: 'it', cefrLevel: 'A1', title: 'Presente Indicativo: Verbi Regolari (-ARE)', grammarPoint: 'presente-italiano-are', explanation: 'I verbi italiani regolari che terminano in -ARE seguono una coniugazione fissa.', shortExplanation: '-o, -i, -a, -iamo, -ate, -ano', difficulty: 1, examples: [{ sentence: 'Io parlo italiano.', translation: 'I speak Italian.' }, { sentence: 'Lei canta bene.', translation: 'She sings well.' }], rules: ['Radice + desinenza: -o, -i, -a, -iamo, -ate, -ano'], exceptions: ['Verbi in -CARE/-GARE: aggiungono h (cerco, paghi)'], commonMistakes: [{ mistake: 'Io parlo italiano' }], relatedLessons: ['presente-italiano-ere', 'presente-italiano-ire'] },
  { languageCode: 'it', cefrLevel: 'A2', title: 'Passato Prossimo', grammarPoint: 'passato-prossimo', explanation: 'Il passato prossimo esprime un\'azione passata completata.', shortExplanation: 'avere/essere + participio passato', difficulty: 2, examples: [{ sentence: 'Ho mangiato la pizza.', translation: 'I ate pizza.' }, { sentence: 'Sono andato a Roma.', translation: 'I went to Rome.' }], rules: ['La maggior parte dei verbi usa avere', 'I verbi di movimento e stato usano essere'], exceptions: ['Participi irregolari: prendere → preso, fare → fatto, dire → detto', 'Con essere, il participio concorda con il soggetto'], commonMistakes: [{ mistake: 'Ho andato a Roma', correct: 'Sono andato a Roma' }], relatedLessons: ['presente-italiano-are', 'participi-passati'] },
  { languageCode: 'it', cefrLevel: 'B1', title: 'Congiuntivo Presente', grammarPoint: 'congiuntivo-presente', explanation: 'Il congiuntivo esprime opinioni, dubbi, desideri e sentimenti.', shortExplanation: 'Forma verbale per esprimere soggettività', difficulty: 3, examples: [{ sentence: 'Penso che lui abbia ragione.', translation: 'I think he is right.' }, { sentence: 'Spero che tu stia bene.', translation: 'I hope you are well.' }], rules: ['Verbi -ARE: -i, -i, -i, -iamo, -iate, -ino', 'Verbi -ERE/-IRE: -a, -a, -a, -iamo, -iate, -ano'], exceptions: ['Essere: sia, sia, sia, siamo, siate, siano', 'Avere: abbia, abbia, abbia, abbiamo, abbiate, abbiano'], commonMistakes: [{ mistake: 'Penso che lui ha ragione', correct: 'Penso che lui abbia ragione' }], relatedLessons: ['indicativo-vs-congiuntivo', 'congiuntivo-imperfetto'] },
  { languageCode: 'it', cefrLevel: 'A2', title: 'Articoli Determinativi e Indeterminativi', grammarPoint: 'articoli-italiani', explanation: 'Gli articoli italiani concordano in genere e numero con il nome.', shortExplanation: 'il/lo/la/i/gli/le = the, un/una/un\' = a', difficulty: 1, examples: [{ sentence: 'Il libro è sul tavolo.', translation: 'The book is on the table.' }, { sentence: 'Ho comprato una mela.', translation: 'I bought an apple.' }], rules: ['Maschile: il (normale), lo (davanti a s+cons, z, gn, ps, x)', 'Femminile: la', 'Plurale: i (maschile), gli (maschile davanti a vocale/s+cons), le (femminile)'], exceptions: [], commonMistakes: [{ mistake: 'Il studente (should be lo studente)', correct: 'Lo studente' }], relatedLessons: ['presente-italiano-are', 'genere-numeri'] },
  { languageCode: 'it', cefrLevel: 'B1', title: 'Pronomi Diretti e Indiretti', grammarPoint: 'pronomi-italiani', explanation: 'I pronomi diretti (lo, la, li, le) e indiretti (gli, le) sostituiscono i complementi.', shortExplanation: 'Diretti: mi/ti/lo/la/ci/vi/li/le — Indiretti: mi/ti/gli/le/ci/vi/gli', difficulty: 3, examples: [{ sentence: 'Vedo Maria. La vedo.', translation: 'I see Maria. I see her.' }, { sentence: 'Do il libro a Marco. Gli do il libro.', translation: 'I give the book to Marco. I give him the book.' }], rules: ['Diretti: mi (me), ti (you), lo (him/it), la (her/it), ci (us), vi (you pl), li (them m), le (them f)', 'Indiretti: mi (to me), ti (to you), gli (to him), le (to her), ci (to us), vi (to you pl), gli (to them)'], exceptions: ['Con passato prossimo, i pronomi diretti fanno concordare il participio'], commonMistakes: [{ mistake: 'Vedo lui instead of Lo vedo', correct: 'Lo vedo' }], relatedLessons: ['passato-prossimo', 'doppi-pronomi'] },

  // ── Portuguese ──
  { languageCode: 'pt', cefrLevel: 'A1', title: 'Presente do Indicativo: Verbos Regulares (-AR)', grammarPoint: 'presente-portugues-ar', explanation: 'Os verbos regulares terminados em -AR seguem um padrão fixo no presente.', shortExplanation: '-o, -as, -a, -amos, -ais, -am', difficulty: 1, examples: [{ sentence: 'Eu falo português.', translation: 'I speak Portuguese.' }, { sentence: 'Ela canta muito bem.', translation: 'She sings very well.' }], rules: ['Tirar -AR e adicionar: -o, -as, -a, -amos, -ais, -am'], exceptions: [], commonMistakes: [{ mistake: 'Eu falar português', correct: 'Eu falo português' }], relatedLessons: ['presente-portugues-er', 'presente-portugues-ir'] },
  { languageCode: 'pt', cefrLevel: 'B1', title: 'Pretérito Perfeito vs Imperfeito', grammarPoint: 'pret-perfeito-vs-imperfeito', explanation: 'O pretérito perfeito expressa ações concluídas; o imperfeito expressa ações habituais ou contínuas no passado.', shortExplanation: 'Perfeito = ação concluída; Imperfeito = ação habitual/contínua', difficulty: 3, examples: [{ sentence: 'Ontem eu estudei muito.', translation: 'Yesterday I studied a lot.' }, { sentence: 'Quando era criança, eu estudava todos os dias.', translation: 'When I was a child, I studied every day.' }], rules: ['Perfeito: ações pontuais e concluídas no passado', 'Imperfeito: ações habituais, descrições, ações em andamento no passado'], exceptions: [], commonMistakes: [{ mistake: 'Quando era criança, eu estudei todos os dias', correct: 'Quando era criança, eu estudava todos os dias' }], relatedLessons: ['presente-portugues-ar', 'futuro-portugues'] },
  { languageCode: 'pt', cefrLevel: 'A2', title: 'Ser vs Estar (Português)', grammarPoint: 'ser-estar-portugues', explanation: 'Tal como em espanhol, ser e estar têm usos distintos em português.', shortExplanation: 'Ser = permanente, Estar = temporário', difficulty: 2, examples: [{ sentence: 'Sou do Brasil.', translation: 'I am from Brazil.' }, { sentence: 'Estou cansado.', translation: 'I am tired.' }], rules: ['Ser: identidade, origem, profissão, características permanentes', 'Estar: estado temporário, localização, emoções'], exceptions: [], commonMistakes: [{ mistake: 'Estou médico', correct: 'Sou médico' }], relatedLessons: ['presente-portugues-ar', 'adjetivos-basicos'] },
  { languageCode: 'pt', cefrLevel: 'A2', title: 'Futuro do Presente', grammarPoint: 'futuro-presente-portugues', explanation: 'O futuro do presente expressa ações que ocorrerão no futuro.', shortExplanation: '-ei, -ás, -á, -emos, -eis, -ão', difficulty: 2, examples: [{ sentence: 'Eu falarei com você amanhã.', translation: 'I will speak with you tomorrow.' }, { sentence: 'Eles viajarão para Portugal.', translation: 'They will travel to Portugal.' }], rules: ['Adicionar as terminações ao infinitivo: -ei, -ás, -á, -emos, -eis, -ão'], exceptions: ['Fazer → farei, Dizer → direi, Trazer → trarei'], commonMistakes: [{ mistake: 'Eu vai falar (using ir incorrectly)', correct: 'Eu falarei' }], relatedLessons: ['presente-portugues-ar', 'preposicoes'] },

  // ── Japanese ──
  { languageCode: 'ja', cefrLevel: 'A1', title: 'です (Desu) - To Be', grammarPoint: 'desu', explanation: 'です is used to end polite sentences, similar to "am/is/are". It declares or describes.', shortExplanation: 'です = am/is/are (polite)', difficulty: 1, examples: [{ sentence: '私は学生です。', translation: 'I am a student.' }, { sentence: 'これは本です。', translation: 'This is a book.' }], rules: ['Put です at the end of a sentence to make it polite', 'Use ではありません for negative'], exceptions: ['Adjectives connect directly without です (during casual speech)'], commonMistakes: [{ mistake: '私学生です (missing は particle)', correct: '私は学生です' }], relatedLessons: ['particles-wa-ga', 'adjectives-i'] },
  { languageCode: 'ja', cefrLevel: 'A2', title: 'て形 (Te-Form)', grammarPoint: 'te-form', explanation: 'The te-form connects verbs for requests, progressive actions, and more.', shortExplanation: 'Verb て form is used for requests and connections', difficulty: 2, examples: [{ sentence: '本を読んでいます。', translation: 'I am reading a book.' }, { sentence: '窓を開けてください。', translation: 'Please open the window.' }], rules: ['う/つ/る → って', 'む/ぬ/ぶ → んで', 'く → いて, ぐ → いで', 'す → して', 'Vowel-stem: add て'], exceptions: ['行く → 行って (irregular)', 'する → して, 来る → 来て'], commonMistakes: [{ mistake: '読むて (should be 読んで)', correct: '読んで' }], relatedLessons: ['desu', 'masu-form'] },
  { languageCode: 'ja', cefrLevel: 'B1', title: '受身形 (Passive Form)', grammarPoint: 'passive-japanese', explanation: 'The passive form is used when the subject receives the action.', shortExplanation: 'Verb ending changes to られる', difficulty: 3, examples: [{ sentence: '私は先生にほめられた。', translation: 'I was praised by the teacher.' }, { sentence: 'この本は多くの人に読まれている。', translation: 'This book is read by many people.' }], rules: ['Group 1 (Godan): change last syllable to あ段 + れる', 'Group 2 (Ichidan): replace る with られる', 'Group 3 (Irregular): する→される, 来る→来られる'], exceptions: [], commonMistakes: [{ mistake: '私はたたいた (active instead of passive)', correct: '私はたたかれた' }], relatedLessons: ['te-form', 'causative-form'] },

  // ── Korean ──
  { languageCode: 'ko', cefrLevel: 'A1', title: '입니다 (imnida) - To Be', grammarPoint: 'imnida', explanation: '입니다 is the formal polite form of "to be" in Korean, used in declarative sentences.', shortExplanation: '입니다 = am/is/are (formal)', difficulty: 1, examples: [{ sentence: '저는 학생입니다.', translation: 'I am a student.' }, { sentence: '이것은 책입니다.', translation: 'This is a book.' }], rules: ['Nouns + 입니다 for "is/are"', 'Nouns + 입니까? for questions', 'Nouns + 이/가 아닙니다 for negative'], exceptions: [], commonMistakes: [{ mistake: '저 학생입니다 (missing topic particle)', correct: '저는 학생입니다' }], relatedLessons: ['particles-eun-neun', 'hajyo-speech'] },
  { languageCode: 'ko', cefrLevel: 'A2', title: '해요체 (Haeyoche - Polite Speech)', grammarPoint: 'haeyoche', explanation: '해요체 is the polite informal speech level used in everyday conversation.', shortExplanation: '-아요/어요 for polite informal speech', difficulty: 2, examples: [{ sentence: '학교에 가요.', translation: 'I go to school.' }, { sentence: '김치를 먹어요.', translation: 'I eat kimchi.' }], rules: ['Verb stem + 아요 if last vowel is ㅏ or ㅗ', 'Verb stem + 어요 for all other vowels', '하다 → 해요'], exceptions: ['이다 → 이에요/예요'], commonMistakes: [{ mistake: '가요 (correct) vs 가요 (used incorrectly)', correct: '가요' }], relatedLessons: ['imnida', 'verb-conjugation'] },
];

const CONVERSATION_SCENARIOS = [
  { languageCode: 'en', cefrLevel: 'A1', scenario: 'ordering-food', title: 'Ordering Food at a Restaurant', description: 'Practice ordering food and drinks at a casual restaurant.', context: 'You are at a restaurant. The server will greet you and take your order.', difficulty: 1, roles: ['Student (customer)', 'AI (server)'], vocabulary: ['menu', 'order', 'bill', 'drink', 'food'], phrases: ['I would like...', 'Can I have...?', 'How much is...?'], tips: ['Start with a greeting', 'Use "please" and "thank you"', 'Specify quantities clearly'], sortOrder: 1 },
  { languageCode: 'en', cefrLevel: 'A1', scenario: 'introducing-self', title: 'Introducing Yourself', description: 'Practice introducing yourself to new people.', context: 'You meet someone new at a social event. Introduce yourself and ask basic questions.', difficulty: 1, roles: ['Student (yourself)', 'AI (new acquaintance)'], vocabulary: ['name', 'from', 'live', 'work', 'study'], phrases: ['My name is...', 'I am from...', 'Nice to meet you'], tips: ['Smile and make eye contact', 'Ask follow-up questions', 'Share one interesting fact'], sortOrder: 2 },
  { languageCode: 'en', cefrLevel: 'A1', scenario: 'asking-directions', title: 'Asking for Directions', description: 'Practice asking for and giving directions.', context: 'You are lost in a new city. Ask a friendly local for help finding your destination.', difficulty: 1, roles: ['Student (traveler)', 'AI (local)'], vocabulary: ['left', 'right', 'straight', 'corner', 'block'], phrases: ['Excuse me...', 'How do I get to...?', 'Is it far?'], tips: ['Start with "Excuse me"', 'Repeat directions to confirm', 'Thank the person'], sortOrder: 3 },
  { languageCode: 'en', cefrLevel: 'A2', scenario: 'shopping', title: 'Shopping for Clothes', description: 'Practice shopping for clothes and interacting with a shop assistant.', context: 'You are in a clothing store looking for a specific item.', difficulty: 2, roles: ['Student (customer)', 'AI (shop assistant)'], vocabulary: ['size', 'color', 'fit', 'try on', 'receipt'], phrases: ['Do you have this in...?', 'Can I try this on?', 'How much does it cost?'], tips: ['Know your sizes', 'Ask about returns', 'Compare options'], sortOrder: 4 },
  { languageCode: 'en', cefrLevel: 'A2', scenario: 'making-appointment', title: 'Making an Appointment', description: 'Practice scheduling appointments in professional settings.', context: 'You need to schedule a meeting with your manager or make a doctor\'s appointment.', difficulty: 2, roles: ['Student (caller)', 'AI (receptionist/manager)'], vocabulary: ['appointment', 'schedule', 'available', 'confirm', 'cancel'], phrases: ['I would like to make an appointment...', 'Is [time] available?', 'Can I reschedule?'], tips: ['Have your calendar ready', 'Confirm the date and time', 'Ask for confirmation email'], sortOrder: 5 },
  { languageCode: 'en', cefrLevel: 'A2', scenario: 'small-talk', title: 'Making Small Talk', description: 'Practice casual conversation about everyday topics.', context: 'You are at a party or social gathering. Start a conversation with someone.', difficulty: 2, roles: ['Student (yourself)', 'AI (conversation partner)'], vocabulary: ['weather', 'weekend', 'hobby', 'movie', 'music'], phrases: ['How was your weekend?', 'Do you like...?', 'That sounds fun!'], tips: ['Ask open-ended questions', 'Share something about yourself', 'Avoid controversial topics'], sortOrder: 6 },
  { languageCode: 'en', cefrLevel: 'B1', scenario: 'hotel-checkin', title: 'Hotel Check-in', description: 'Practice checking into a hotel and handling common situations.', context: 'You are arriving at a hotel after a long trip. Check in and address any issues.', difficulty: 3, roles: ['Student (guest)', 'AI (hotel receptionist)'], vocabulary: ['reservation', 'check-in', 'room', 'key card', 'amenities'], phrases: ['I have a reservation under...', 'Is breakfast included?', 'There is a problem with...'], tips: ['Have your ID and booking ready', 'Ask about amenities', 'Note the check-out time'], sortOrder: 7 },
  { languageCode: 'en', cefrLevel: 'B1', scenario: 'job-interview', title: 'Job Interview Practice', description: 'Practice answering common job interview questions.', context: 'You are interviewing for a job. Answer questions about your experience and skills.', difficulty: 3, roles: ['Student (candidate)', 'AI (interviewer)'], vocabulary: ['experience', 'skills', 'qualifications', 'strengths', 'teamwork'], phrases: ['I have experience in...', 'My greatest strength is...', 'I am looking for...'], tips: ['Use specific examples', 'Show enthusiasm', 'Prepare questions to ask'], sortOrder: 8 },
  { languageCode: 'en', cefrLevel: 'B1', scenario: 'emergency', title: 'Emergency Situations', description: 'Practice communicating during emergencies.', context: 'You need help in an emergency situation. Clearly state the problem.', difficulty: 3, roles: ['Student (person in need)', 'AI (emergency operator / helper)'], vocabulary: ['help', 'emergency', 'ambulance', 'police', 'accident'], phrases: ['I need help!', 'There has been an accident...', 'Please send...'], tips: ['Stay calm', 'Speak clearly', 'Give your location first'], sortOrder: 9 },
  { languageCode: 'en', cefrLevel: 'B1', scenario: 'discussing-opinions', title: 'Discussing Opinions', description: 'Practice expressing and defending your opinions on topics.', context: 'You are in a discussion group. Share your views on a current topic.', difficulty: 3, roles: ['Student (participant)', 'AI (discussion moderator)'], vocabulary: ['opinion', 'agree', 'disagree', 'however', 'therefore'], phrases: ['In my opinion...', 'I agree because...', 'I see your point, but...'], tips: ['Respect different views', 'Use examples to support your point', 'Learn polite disagreement phrases'], sortOrder: 10 },
  { languageCode: 'en', cefrLevel: 'A2', scenario: 'at-the-doctor', title: 'At the Doctor\'s Office', description: 'Practice describing symptoms and understanding medical advice.', context: 'You are feeling unwell and visit a doctor. Describe your symptoms.', difficulty: 2, roles: ['Student (patient)', 'AI (doctor)'], vocabulary: ['headache', 'fever', 'pain', 'medicine', 'rest'], phrases: ['I have a...', 'It hurts when...', 'What should I do?'], tips: ['Describe when symptoms started', 'Mention any allergies', 'Ask about medication'], sortOrder: 11 },
  { languageCode: 'en', cefrLevel: 'A2', scenario: 'at-the-bank', title: 'At the Bank', description: 'Practice common bank transactions and conversations.', context: 'You need to open an account or perform a transaction at the bank.', difficulty: 2, roles: ['Student (customer)', 'AI (bank teller)'], vocabulary: ['account', 'deposit', 'withdraw', 'balance', 'transfer'], phrases: ['I would like to open...', 'Can I withdraw...?', 'What is my balance?'], tips: ['Bring identification', 'Know what type of account you need', 'Ask about fees'], sortOrder: 12 },
  { languageCode: 'en', cefrLevel: 'B1', scenario: 'renting-apartment', title: 'Renting an Apartment', description: 'Practice conversations with landlords or rental agents.', context: 'You are looking for an apartment to rent. Ask about the property.', difficulty: 3, roles: ['Student (tenant)', 'AI (landlord/agent)'], vocabulary: ['rent', 'deposit', 'lease', 'utilities', 'furnished'], phrases: ['How much is the rent?', 'Is it furnished?', 'Are utilities included?'], tips: ['Read the lease carefully', 'Ask about maintenance', 'Inspect the property'], sortOrder: 13 },
  { languageCode: 'en', cefrLevel: 'B1', scenario: 'travel-planning', title: 'Planning a Trip', description: 'Practice discussing travel plans with a travel agent or friend.', context: 'You are planning a vacation. Discuss destinations, budgets, and activities.', difficulty: 3, roles: ['Student (traveler)', 'AI (travel agent)'], vocabulary: ['destination', 'budget', 'flight', 'hotel', 'itinerary'], phrases: ['I am planning to...', 'What do you recommend?', 'How much does it cost?'], tips: ['Set a budget first', 'Research the destination', 'Book in advance for better deals'], sortOrder: 14 },
  { languageCode: 'en', cefrLevel: 'A1', scenario: 'at-the-supermarket', title: 'At the Supermarket', description: 'Practice shopping for groceries.', context: 'You are at the supermarket looking for items. Ask the shop assistant for help.', difficulty: 1, roles: ['Student (shopper)', 'AI (shop assistant)'], vocabulary: ['bread', 'milk', 'fruit', 'price', 'bag'], phrases: ['Where can I find...?', 'How much is this?', 'I need...'], tips: ['Make a shopping list', 'Compare prices', 'Check expiry dates'], sortOrder: 15 },
  { languageCode: 'en', cefrLevel: 'A2', scenario: 'using-public-transport', title: 'Using Public Transport', description: 'Practice buying tickets and asking about public transport.', context: 'You need to use the bus or train. Ask about routes and fares.', difficulty: 2, roles: ['Student (passenger)', 'AI (ticket seller / information)'], vocabulary: ['ticket', 'platform', 'schedule', 'fare', 'route'], phrases: ['Which platform?', 'How much is a ticket to...?', 'When is the next...?'], tips: ['Check the schedule', 'Have the exact fare ready', 'Validate your ticket'], sortOrder: 16 },
  { languageCode: 'en', cefrLevel: 'B1', scenario: 'social-media', title: 'Discussing Social Media', description: 'Practice discussing social media habits and digital life.', context: 'Talk with a friend about how you use social media and technology.', difficulty: 3, roles: ['Student (yourself)', 'AI (friend)'], vocabulary: ['social media', 'privacy', 'follow', 'post', 'online'], phrases: ['I spend too much time on...', 'Do you follow...?', 'I think privacy is important because...'], tips: ['Be mindful of screen time', 'Think before you post', 'Protect your privacy'], sortOrder: 17 },
  { languageCode: 'en', cefrLevel: 'B1', scenario: 'giving-presentation', title: 'Giving a Short Presentation', description: 'Practice presenting a topic to a small audience.', context: 'You need to give a 2-minute presentation on a familiar topic.', difficulty: 3, roles: ['Student (presenter)', 'AI (audience member)'], vocabulary: ['presentation', 'slide', 'introduction', 'conclusion', 'question'], phrases: ['Today I will talk about...', 'First, let me introduce...', 'Are there any questions?'], tips: ['Structure your talk: intro-body-conclusion', 'Make eye contact', 'Speak slowly and clearly'], sortOrder: 18 },
  { languageCode: 'en', cefrLevel: 'A2', scenario: 'dining-with-friends', title: 'Dining Out with Friends', description: 'Practice splitting bills and making suggestions at a restaurant.', context: 'You are out to eat with friends. Decide what to order and how to split the bill.', difficulty: 2, roles: ['Student (diner)', 'AI (friend/server)'], vocabulary: ['split', 'share', 'treat', 'dessert', 'tip'], phrases: ['Let\'s share...', 'I\'ll have the...', 'Let\'s split the bill.'], tips: ['Agree on how to split beforehand', 'Tip appropriately', 'Try sharing dishes'], sortOrder: 19 },
  { languageCode: 'en', cefrLevel: 'A1', scenario: 'describing-people', title: 'Describing People', description: 'Practice describing people\'s appearance and personality.', context: 'You are describing someone to a friend who is looking for them.', difficulty: 1, roles: ['Student (describer)', 'AI (friend)'], vocabulary: ['tall', 'short', 'young', 'old', 'friendly'], phrases: ['He/she is...', 'He/she has...', 'He/she wears...'], tips: ['Start with general traits', 'Add specific details', 'Describe clothes if relevant'], sortOrder: 20 },
];

async function main() {
  console.log('Seeding vocabulary bank...');
  for (const v of VOCABULARY) {
    await prisma.vocabularyBank.upsert({
      where: { languageCode_word: { languageCode: v.languageCode, word: v.word } },
      update: {},
      create: v,
    });
  }
  console.log(`Seeded ${VOCABULARY.length} vocabulary items`);

  console.log('Seeding grammar lessons...');
  for (const g of GRAMMAR_LESSONS) {
    await prisma.grammarLesson.upsert({
      where: { languageCode_grammarPoint: { languageCode: g.languageCode, grammarPoint: g.grammarPoint } },
      update: {},
      create: g as any,
    });
  }
  console.log(`Seeded ${GRAMMAR_LESSONS.length} grammar lessons`);

  console.log('Seeding conversation scenarios...');
  for (const c of CONVERSATION_SCENARIOS) {
    await prisma.conversationScenario.upsert({
      where: { languageCode_scenario: { languageCode: c.languageCode, scenario: c.scenario } },
      update: {},
      create: c as any,
    });
  }
  console.log(`Seeded ${CONVERSATION_SCENARIOS.length} conversation scenarios`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
